### ISSUE TITLE
Should add the Coco Town youtube channel to the list

### ISSUE THREAD

**Issue by Tape-Worm** [dougmasten/awesome-coco#9]
There's a series of videos of a guy taking an old game he wrote for his coco in high school and bringing it up to snuff with his updated knowledge now that he's an adult.

https://www.youtube.com/@CocoTownRetro

I think it'd be a perfect fit for this list.

**Comment by dougmasten** [comment]
Yes, awesome channel. I can't believe it wasn't already added. It's now added. Thanks!
